static_library("hello") {
  sources = [
    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c4_nfc/src/ndef.c",
    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c4_nfc/src/nfc.c",
    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c4_nfc/src/nfcForum.c",
    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c4_nfc/src/NT3H.c",
    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c4_nfc/src/rtdText.c",
    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c4_nfc/src/rtdUri.c",
    
    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c3_eeprom/src/eeprom.c",

    "hello.c",
    "src/lcd.c",
    "src/components.c",
    "src/smart_home.c",
    "src/smart_home_event.c",
    "src/su_03t.c",
    "src/iot.c" ,
    "src/picture.c" ,
    "src/adc_key.c" ,
    "src/drv_light.c",
    "src/drv_motor.c",
    "src/drv_sensors.c",
    
    "src/mq2.c"
  ]

  include_dirs = [
    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c4_nfc/include",

    "/home/openharmony/txsmartropenharmony/vendor/isoftstone/rk2206/samples/c3_eeprom/include",

    "//utils/native/lite/include",
    "include",
    "src/include" ,
    "//kernel/liteos_m/components/shell/include",
    "//base/iot_hardware/peripheral/interfaces/kits",
    "//device/rockchip/rk2206/adapter/include",
    "//device/rockchip/rk2206/sdk_liteos/board/include",
    "//device/rockchip/hardware/lib/hal/inc",
    "//device/rockchip/hardware/lib/CMSIS/Device/RK2206/Include/",
    "//third_party/cJSON",
    "//third_party/musl/porting/liteos_m/kernel/include",
    "//third_party/paho_mqtt/MQTTPacket/src",
    "//third_party/paho_mqtt/MQTTClient-C/src",
  ]

  deps = [ "//device/rockchip/hardware:hardware" ]
}